# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170516_1256'),
        ('core', '0003_auto_20170516_1218'),
    ]

    operations = [
    ]
