# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-01 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='facebook_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='twitter_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
