# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


def gen_uuid(apps, schema_editor):
    Article = apps.get_model('dispatch', 'article')
    for row in Article.objects.all():
        row.preview_id = uuid.uuid4()
        row.save()

    Page = apps.get_model('dispatch', 'page')
    for row in Page.objects.all():
        row.preview_id = uuid.uuid4()
        row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_add_preview_id'),
    ]

    operations = [
    	migrations.RunPython(gen_uuid),
    ]
