# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-25 21:39
from __future__ import unicode_literals

from django.db import migrations, models

def move_authors(apps, schema_editor):
    Author = apps.get_model('dispatch', 'Author')
    Article = apps.get_model('dispatch', 'Article')
    Image = apps.get_model('dispatch', 'Image')

    for article in Article.objects.all():
        for author in Author.objects.filter(article_id=article.id):
            article.authors.add(author)
        article.save()

    for image in Image.objects.all():
        for author in Author.objects.filter(image_id=image.id):
            image.authors.add(author)
        image.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0006_author_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(related_name='article_authors', to='dispatch.Author'),
        ),
        migrations.RemoveField(
            model_name='image',
            name='authors',
        ),
        migrations.AddField(
            model_name='image',
            name='authors',
            field=models.ManyToManyField(related_name='image_authors', to='dispatch.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='type',
            field=models.CharField(blank=True, default=b'author', max_length=100),
        ),
    	migrations.RunPython(move_authors),
        migrations.RemoveField(
            model_name='author',
            name='article',
        ),
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
]
