# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0008_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='img',
            field=models.ImageField(upload_to=b'images/%Y/%m'),
        ),
    ]
