# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 16:17
from __future__ import unicode_literals

from django.db import migrations, models


def set_defaults(apps, schema_editor):
    Topic = apps.get_model('dispatch', 'Topic')

    for topic in Topic.objects.all().iterator():
        topic.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0008_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='', blank=True, unique=False),
        ),
        migrations.RunPython(set_defaults),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
