# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0009_auto_20180328_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='file',
        ),
        migrations.AddField(
            model_name='issue',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
