# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0010_remove_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('permissions', models.CharField(default=b'', max_length=255)),
                ('expiration_date', models.DateTimeField()),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invited_person', to='dispatch.Person')),
            ],
        ),
    ]
