# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0010_auto_20180330_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='url',
        ),
        migrations.AddField(
            model_name='issue',
            name='file',
            field=models.FileField(default='', upload_to=b'issues/%Y/%m'),
            preserve_default=False,
        ),
    ]
