# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0011_auto_20180508_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='url',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
