# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0011_auto_20180404_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='img',
            field=models.ImageField(default='', upload_to=b'images/%Y/%m'),
            preserve_default=False,
        ),
    ]
