# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 21:54
from __future__ import unicode_literals

import dispatch.modules.content.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0012_polls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(null=True)),
                ('articles', models.ManyToManyField(related_name='column_articles', to='dispatch.Article')),
                ('authors', models.ManyToManyField(related_name='column_authors', to='dispatch.Author')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='column_featured_image', to='dispatch.ImageAttachment')),
            ],
            bases=(models.Model, dispatch.modules.content.mixins.AuthorMixin),
        ),
        migrations.AddField(
            model_name='article',
            name='column',
            field=models.ManyToManyField(related_name='article_column', to='dispatch.Column'),
        ),
    ]
