# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0012_polls'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_breaking',
            field=models.BooleanField(default=False),
        ),
    ]
