# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0012_issue_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='volume',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
