# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 20:47
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0012_polls'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='template_required',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='page',
            name='template_required',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
