# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0013_image_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='test_field',
        ),
    ]
