# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 18:59
from __future__ import unicode_literals

import dispatch.modules.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0013_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='expiration_date',
            field=models.DateTimeField(default=dispatch.modules.auth.models.get_expiration_date),
        ),
    ]
