# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0014_auto_20180724_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='style',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
