# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0015_image_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='style',
        ),
        migrations.AddField(
            model_name='imageattachment',
            name='width',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
