# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0015_auto_20180628_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='expirationtime',
        ),
    ]
