# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0017_auto_20180628_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='auth',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='p256dh',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
