# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0017_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True, unique=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
