# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0017_subsections'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=b'')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=b'')),
                ('duration', models.PositiveIntegerField()),
                ('published_at', models.DateTimeField()),
                ('explicit', models.BooleanField()),
                ('file', models.FileField(upload_to=b'')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch.Podcast')),
            ],
        ),
    ]
