# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0018_podcast_podcastepisode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch.Image'),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch.Image'),
        ),
    ]
