# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0020_topic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='explicit',
            field=models.CharField(choices=[(b'No', b'No'), (b'Yes', b'Yes'), (b'Clean', b'Clean')], default=b'No', max_length=5),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='category',
            field=models.CharField(choices=[(b'Arts', b'Arts'), (b'Business', b'Business'), (b'Comedy', b'Comedy'), (b'Education', b'Education'), (b'Games &amp; Hobbies', b'Games & Hobbies'), (b'Government &amp; Organizations', b'Government & Organizations'), (b'Health', b'Health'), (b'Kids &amp; Family', b'Kids & Family'), (b'Music', b'Music'), (b'News &amp; Politics', b'News & Politics'), (b'Religion &amp; Spirituality', b'Religion & Spirituality'), (b'Science &amp; Medicine', b'Science & Medicine'), (b'Society &amp; Culture', b'Society & Culture'), (b'Sports &amp; Recreation', b'Sports & Recreation'), (b'Technology', b'Technology'), (b'TV &amp; Film', b'TV & Film')], default=b'Arts', max_length=255),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='explicit',
            field=models.CharField(choices=[(b'No', b'No'), (b'Yes', b'Yes'), (b'Clean', b'Clean')], default=b'No', max_length=5),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
