# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0021_podcast_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
