# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-05 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0021_podcast_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='authors',
            field=models.ManyToManyField(related_name='video_authors', to='dispatch.Author'),
        ),
        migrations.AddField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(to='dispatch.Tag'),
        ),
        migrations.AddField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]