# Generated by Django 2.2.2 on 2019-06-07 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0022_video_meta_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_parent', to='dispatch.Article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='reading_time',
            field=models.CharField(choices=[('anytime', 'Anytime'), ('morning', 'Morning'), ('midday', 'Midday'), ('evening', 'Evening')], default='anytime', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_subsection', to='dispatch.Subsection'),
        ),
        migrations.AlterField(
            model_name='article',
            name='template',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatch.Topic'),
        ),
        migrations.AlterField(
            model_name='author',
            name='type',
            field=models.CharField(blank=True, default='author', max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='imageattachment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_article', to='dispatch.Article'),
        ),
        migrations.AlterField(
            model_name='imageattachment',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatch.ImageGallery'),
        ),
        migrations.AlterField(
            model_name='imageattachment',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_page', to='dispatch.Page'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='settings',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='permissions',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='file',
            field=models.FileField(upload_to='issues/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='img',
            field=models.ImageField(upload_to='images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_parent', to='dispatch.Page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_page_fk', to='dispatch.Page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='category',
            field=models.CharField(choices=[('Arts', 'Arts'), ('Business', 'Business'), ('Comedy', 'Comedy'), ('Education', 'Education'), ('Games &amp; Hobbies', 'Games & Hobbies'), ('Government &amp; Organizations', 'Government & Organizations'), ('Health', 'Health'), ('Kids &amp; Family', 'Kids & Family'), ('Music', 'Music'), ('News &amp; Politics', 'News & Politics'), ('Religion &amp; Spirituality', 'Religion & Spirituality'), ('Science &amp; Medicine', 'Science & Medicine'), ('Society &amp; Culture', 'Society & Culture'), ('Sports &amp; Recreation', 'Sports & Recreation'), ('Technology', 'Technology'), ('TV &amp; Film', 'TV & Film')], default='Arts', max_length=255),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='explicit',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Clean', 'Clean')], default='No', max_length=5),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatch.Image'),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='explicit',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Clean', 'Clean')], default='No', max_length=5),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='file',
            field=models.FileField(upload_to='podcasts/'),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatch.Image'),
        ),
        migrations.AlterField(
            model_name='videoattachment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_article', to='dispatch.Article'),
        ),
        migrations.AlterField(
            model_name='videoattachment',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_page', to='dispatch.Page'),
        ),
    ]
