# Generated by Django 2.2.2 on 2019-07-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0023_upgrade_to_django2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(default='default_full_name', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(default='default_slug', unique=True),
            preserve_default=False,
        ),
    ]
