# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-05 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0100_publishable_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='head',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_active',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='page',
            name='head',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_active',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.NullBooleanField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
