# Generated by Django 3.0.7 on 2020-09-19 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0101_publishable_constraints_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='banner_timeout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subsection',
            name='banner_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subsection',
            name='subsection_banner_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
