# Generated by Django 3.1.8 on 2021-05-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0102_auto_20200921_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
        migrations.RemoveField(
            model_name='page',
            name='views',
        ),
        migrations.AlterField(
            model_name='article',
            name='head',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='head',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
    ]
