# Generated by Django 3.1.8 on 2021-05-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0103_auto_20210505_0050'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_at'], name='dispatch_ar_publish_cc3607_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['head', 'is_published'], name='dispatch_ar_head_faebef_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['section'], name='dispatch_ar_section_6fccdb_idx'),
        ),
    ]
