# Generated by Django 3.1.8 on 2021-05-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0105_auto_20210507_1600'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['img'], name='dispatch_im_img_51336a_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['slug'], name='dispatch_se_slug_ec3dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='subsection',
            index=models.Index(fields=['slug'], name='dispatch_su_slug_e46305_idx'),
        ),
    ]
