# Generated by Django 3.1.8 on 2021-05-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0107_auto_20210511_1354'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['subsection'], name='dispatch_ar_subsect_f813dd_idx'),
        ),
    ]
