# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 22:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('host', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'events/')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=500)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(choices=[(b'sports', b'Sports'), (b'music', b'Music'), (b'academic', b'Academic'), (b'party', b'Party'), (b'business', b'Business'), (b'ceremony', b'Ceremony'), (b'workshop', b'Workshop'), (b'other', b'Other')], max_length=20)),
                ('facebook_url', models.TextField(blank=True, max_length=500, null=True)),
                ('facebook_image_url', models.TextField(blank=True, max_length=500, null=True)),
                ('is_submission', models.BooleanField(default=False)),
                ('submitter_email', models.EmailField(max_length=254, null=True)),
                ('submitter_phone', models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message=b'Please enter a valid phone number', regex=b'(\\+?1-)?\\(?([0-9]){3}(\\)?)(|\\s?|-?|\\.?)([0-9]){3}(\\)?|\\s?|-?|\\.?)([0-9]{4})$')])),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
