# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('template_slug', models.CharField(max_length=255)),
                ('variable', models.CharField(max_length=50)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.SlugField(primary_key=True, serialize=False)),
                ('widget_id', models.SlugField(null=True)),
                ('data', jsonfield.fields.JSONField(null=True)),
            ],
        ),
    ]
