# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20170516_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='id',
        ),
        migrations.AlterField(
            model_name='zone',
            name='data',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='widget_id',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone_id',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
