# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20170516_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='id',
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone_id',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
